apiVersion: apps/v1
kind: Deployment
metadata:
    name: playwright
spec:
    selector:
        matchLabels:
            app: playwright
    template:
        metadata:
            labels:
                app: playwright
        spec:
            containers:
            - image: playwright
              resources:
                  limits:
                      cpu: 200m
                      memory: 512Mi
              name: playwright
