apiVersion: apps/v1
kind: Deployment
metadata:
    name: playwright
spec:
    selector:
        matchLabels:
            app: playwright
    template:
        metadata:
            labels:
                app: playwright
        spec:
            containers:
            - image: playwright
              resources:
                  requests:
                      memory: 512Mi
                      cpu: "300m"
              name: playwright
