apiVersion: apps/v1
kind: Deployment
metadata:
    name: playwright
spec:
    selector:
        matchLabels:
            app: playwright
    template:
        metadata:
            labels:
                app: playwright
        spec:
            securityContext:
                runAsUser: 2000
            containers:
            - image: playwright
              name: playwright
 
