import selenium.webdriver, time, PIL, io, pytesseract, argparser
options = selenium.webdriver.ChromeOptions()
options.headless = True
options.add_argument('--disable-popup-blocking')
options.add_argument('--incognito')
options.add_argument('--no-first-run')
driver = selenium.webdriver.Chrome(options=options)
driver.get('https://www.alexamaster.net/sec/login.php')
driver.execute_script('globalThis.scrollTo(0,1000)')
time.sleep(10)
driver.find_element_by_css_selector('input[placeholder="Your Email ..."]').send_keys('chaowen.guo1@gmail.com')
driver.find_element_by_css_selector('input[placeholder="Your Password ..."]').send_keys('HL798820y+')
driver.find_element_by_css_selector('input[value="Login Now"]').click()
time.sleep(60)
good = PIL.Image.open(io.BytesIO(driver.get_screenshot_as_png()))
ocr = driver.find_element_by_css_selector('img[src="image.php"]')
ocr = good.crop((ocr.location['x'], ocr.location['y'], ocr.location['x'] + ocr.size['width'], ocr.location['y'] + ocr.size['height'])).convert('L').point(lambda _:255 if _ > 200 else 0)
good.save('good.png')
ocr.save('ocr.png')
print(pytesseract.image_to_string(ocr))
driver.close()
