on:
    push:
    schedule:
    - cron: '0 */6 * * *'
    - cron: '0 */8 * * *'
jobs:
    github:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */6 * * *' 
        strategy:
            matrix:
                node: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 15.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          run: |
              npm install --prefix js playwright-chromium
              node --harmony js/surf.js
    kaggle:
        runs-on: ubuntu-latest
        #if: github.event.schedule == '0 */8 * * *'
        strategy:
            matrix:
                version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - env:
              KAGGLE_USERNAME: chaowenguo
              KAGGLE_KEY: ${{secrets.KAGGLE}}
          run: |
              pip install kaggle
              sed -i 's/VERSION/${{matrix.version}}/g' kernel-metadata.json 
              kaggle kernels push
    #heroku:
        #runs-on: ubuntu-latest
        #if: github.event.schedule == '*/30 * * * *'
        #steps:
        #- uses: actions/chesecrets.HEROKU}}
        #      heroku_app_name: playwrightt
        #      heroku_email: chaowen.guo1@gmail.com
        #      usedocker: true
    docker:
        runs-on: ubuntu-latest
        if: github.event_name != 'push' && github.event_name != 'schedule'
        steps:
        - uses: actions/checkout@main
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: python py/version.py
        - uses: actions/setup-python@main
          with:
              python-version: ${{env.PY}}
        - run: python -m compileall -lb py
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/playwright:py
              context: py
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/playwright:js
              context: js
        - uses: actions/setup-java@main
          with:
              java-version: 15.x
        - run: java java/Version.java
        - uses: actions/setup-java@main
          with:
              java-version: ${{env.JAVA}}
        - run: |
              gradle -p java copyDependencies
              javac -cp java/copyDependencies/*:java java/Surf.java
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/playwright:java
              context: java
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 15.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          run: |
              npm install playwright-chromium
              node --harmony heroku.js
              git add ha.png
              git config user.name dummy
              git config user.email dummy
              git commit --allow-empty-message -m ''
              git push
