on:
    push:
    schedule:
    - cron: '0 */6 * * *'
jobs:
    surf:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        strategy:
            matrix:
                node: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: '15.x'
        - run: |
              npm install playwright
              node --harmony surf.js
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/playwright:py
              file: py.Dockerfile
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/playwright:js
              file: js.Dockerfile
