on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - run: |
              google-chrome --headless --disable-gpu --dump-dom https://v2ex.com/go/jobs     
              pip install aiohttp beautifulsoup4
              python job.py
