on:
    push:
    schedule:
    - cron: '0 */3 * * *'
jobs:
    surf:
        runs-on: ubuntu-latest
        if: github.event_name == 'schedule'
        strategy:
            matrix:
                node: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - run: |
              pip install playwright
              python surf.py
    good:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - run: |
              #sudo apt install --no-install-recommends tesseract-ocr
              #pip install selenium pytesseract
              #python good.py
              pip install playwright
              python surf.py
              #git add -A
              #git config user.name dummy
              #git config user.email dummy
              #git commit --allow-empty-message -m ''
              #git push
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - run: |
              wget https://chromedriver.storage.googleapis.com/`wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/selenium
              context: .
