on:
    push:
    schedule:
    - cron: '0 */6 * * *'
jobs:
    money:
        runs-on: ubuntu-latest
        if: github.event_name == 'schedule'
        strategy:
            matrix:
                node: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - run: |
              pip install selenium pynat
              python surf.py
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/selenium
