on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - run: |
              google-chrome --headless --disable-gpu --dump-dom https://www.chromestatus.com/
              pip install aiohttp beautifulsoup4 selenium chromedriver-binary-auto
              python job.py
