on:
    push:
    schedule:
    - cron: '0 */6 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [6, 8, 10]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - run: |
              pip install selenium pynat
              python main.py
